### ISSUE TITLE
about the GroupNorm3d

### ISSUE THREAD

**Issue by zyfsa** [chengyangfu/pytorch-groupnormalization#1]
hello, how can I use your code implement the GroupNorm3d, Thank you very much

**Comment by chengyangfu** [comment]
Hi @zyfsa, 
    Recently, PyTorch also supports this operation now. I would suggest you check their implementation first. 
    I also update the code to include the 3D case. It passes some simple tests and I believe it is correct. But I never use it to train on the real dataset. So, if you don't mind it, you can try it and see how it works.
