### ISSUE TITLE
The compressed package seems to be damaged

### ISSUE THREAD

**Issue by ChaofWang** [chengyangfu/pytorch-groupnormalization#2]
Hello I try down your link，but it seems to be damaged。Can you provide this link again?

**Comment by chengyangfu** [comment]
Hi @ChaofWang , 
   I just tested the link and code. It works well. Do you have any error message? 
   P.S. Although filename extension is ".tar", you should not untar the file.

**Comment by ChaofWang** [comment]
oh，I see. Thank you！
