### ISSUE TITLE
Reproduced Accuracy

### ISSUE THREAD

**Issue by qiulesun** [chengyangfu/pytorch-groupnormalization#3]
**Reproduced Accuracy**
I use the released model resnet50-groupnorm32 to reproduce your results, and run python main.py IMAGENET_DIR --evaluate --batch-size=100 --arch=resnet50 --group-norm=32  --resume=./resnet50_groupnorm32.tar.
However, I only get 47.250% top-1 acc and 71.727% top-5 acc, repectively, much lower than your reported acc.

**Comment by chengyangfu** [comment]
@qiulesun  This version was developed under PyTorch 3. I think you are using PyTorch 4.0+ which will cause a bug. I will fix it soon.

**Comment by qiulesun** [comment]
Thanks for your reply. I indeed ran your test codes using the PyTorch 1.0 version and python 3.6. I am forward to your next updated codes. Could you share the acc per epoch if possible ?

**Comment by chengyangfu** [comment]
@qiulesun  
    Updated the code. Please download the model and run the code again.
